// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletType int32

const (
	WalletType_BUSINESS WalletType = 0
	WalletType_CUSTOMER WalletType = 1
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "BUSINESS",
		1: "CUSTOMER",
	}
	WalletType_value = map[string]int32{
		"BUSINESS": 0,
		"CUSTOMER": 1,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wallet_proto_enumTypes[0].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_proto_wallet_proto_enumTypes[0]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{0}
}

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type          WalletType             `protobuf:"varint,3,opt,name=type,proto3,enum=proto.WalletType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreateWalletRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateWalletRequest) GetType() WalletType {
	if x != nil {
		return x.Type
	}
	return WalletType_BUSINESS
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type          WalletType             `protobuf:"varint,4,opt,name=type,proto3,enum=proto.WalletType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreateWalletResponse) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreateWalletResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateWalletResponse) GetType() WalletType {
	if x != nil {
		return x.Type
	}
	return WalletType_BUSINESS
}

func (x *CreateWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wallet.proto\x12\x05proto\"~\n" +
	"\x13CreateWalletRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.proto.WalletTypeR\x04type\"\xb6\x01\n" +
	"\x14CreateWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.proto.WalletTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*(\n" +
	"\n" +
	"WalletType\x12\f\n" +
	"\bBUSINESS\x10\x00\x12\f\n" +
	"\bCUSTOMER\x10\x012Z\n" +
	"\rWalletService\x12I\n" +
	"\fCreateWallet\x12\x1a.proto.CreateWalletRequest\x1a\x1b.proto.CreateWalletResponse\"\x00BFZDgithub.com/ronexlemon/rail/micro-services/wallet-service/proto;protob\x06proto3"

var (
	file_proto_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_proto_rawDescData []byte
)

func file_proto_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_proto_rawDescData
}

var file_proto_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_wallet_proto_goTypes = []any{
	(WalletType)(0),              // 0: proto.WalletType
	(*CreateWalletRequest)(nil),  // 1: proto.CreateWalletRequest
	(*CreateWalletResponse)(nil), // 2: proto.CreateWalletResponse
}
var file_proto_wallet_proto_depIdxs = []int32{
	0, // 0: proto.CreateWalletRequest.type:type_name -> proto.WalletType
	0, // 1: proto.CreateWalletResponse.type:type_name -> proto.WalletType
	1, // 2: proto.WalletService.CreateWallet:input_type -> proto.CreateWalletRequest
	2, // 3: proto.WalletService.CreateWallet:output_type -> proto.CreateWalletResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_wallet_proto_init() }
func file_proto_wallet_proto_init() {
	if File_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_proto_depIdxs,
		EnumInfos:         file_proto_wallet_proto_enumTypes,
		MessageInfos:      file_proto_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_proto = out.File
	file_proto_wallet_proto_goTypes = nil
	file_proto_wallet_proto_depIdxs = nil
}
